//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestApp.Web {
    
    
    public partial class FondPortfeljPregled {
        
        /// <summary>
        /// FondPortfeljPregledCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InvestApp.Web.FondPortfeljPregledCtrl FondPortfeljPregledCtrl;
        
        /// <summary>
        /// portfeljVrijednostiGraf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InvestApp.Web.FondPortfeljVrijednostGrafCtrl portfeljVrijednostiGraf;
        
        /// <summary>
        /// portfeljUdioGraf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InvestApp.Web.FondPortfeljUdioGrafCtrl portfeljUdioGraf;
    }
}
