CREATE TABLE [dbo].[FONDOVI_USPOREDBA](
	[FOND_ID] [int] NOT NULL,
	[USPOREDBA_FOND_ID] [int] NOT NULL,
 CONSTRAINT [PK_FONDOVI_USPOREDBA] PRIMARY KEY CLUSTERED 
(
	[FOND_ID] ASC,
	[USPOREDBA_FOND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[FONDOVI_USPOREDBA]  WITH CHECK ADD  CONSTRAINT [FK_FONDOVI_USPOREDBA_FOND_DEF] FOREIGN KEY([FOND_ID])
REFERENCES [dbo].[FOND_DEF] ([ID])
GO

ALTER TABLE [dbo].[FONDOVI_USPOREDBA] CHECK CONSTRAINT [FK_FONDOVI_USPOREDBA_FOND_DEF]
GO

ALTER TABLE [dbo].[FONDOVI_USPOREDBA]  WITH CHECK ADD  CONSTRAINT [FK_FONDOVI_USPOREDBA_FOND_DEF1] FOREIGN KEY([USPOREDBA_FOND_ID])
REFERENCES [dbo].[FOND_DEF] ([ID])
GO

ALTER TABLE [dbo].[FONDOVI_USPOREDBA] CHECK CONSTRAINT [FK_FONDOVI_USPOREDBA_FOND_DEF1]
GO

/**************************************/

INSERT  INTO dbo.FONDOVI_USPOREDBA
        ( FOND_ID ,
          USPOREDBA_FOND_ID
        )
        SELECT  f.ID ,
                ind.ID
        FROM    dbo.FOND_DEF f
                JOIN ( SELECT   ID
                       FROM     dbo.FOND_DEF
                       WHERE    INDEKSNI = 1
                     ) AS ind ON 1 = 1
        WHERE   COALESCE(f.INDEKSNI, 0) = 0

/************************************/

UPDATE f
SET f.USPOREDNI_FOND_ID = IND.ID
FROM dbo.FOND_DEF f JOIN 
(SELECT MIN(ID) AS ID FROM dbo.FOND_DEF WHERE INDEKSNI = 1) AS ind ON 1=1
WHERE COALESCE(f.INDEKSNI, 0) = 0
